version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    platform: linux/amd64
    image: mysql:8.0.26
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: thanh
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
